version: '3.3'
services:
    app:
        container_name: timetable_of_classes
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_SERVER=db
            - POSTGRES_DB=pz
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - DB_PORT=5432

        ports:
            - 1488:8080
        restart: always
        depends_on:
            - db
    db:
        image: postgres
        container_name: postgres
#        ports:
#            - 5555:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always


